### ISSUE TITLE
Menambahkan Deskripsi Repositori

### ISSUE THREAD

**Issue by jefrydco** [cjzeven/youtube-subtitle-finder#1]
Hi Mas Aden, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Aden.

Mas juga sudah menerapkan kerangka kerja Bootstrap untuk aplikasi pencari teks pada video YouTube ini. Selain itu terdapat juga animasi yg menarik saat pertama kali membuka halaman. Luar biasa Mas!

Namun saya ada 1 saran kecil Mas yakni menambahkan deskripsi repositori. Agar repositori kita memiliki deskripsi, Mas bisa menambahkan berkas bernama `readme.md` di dalam direktori proyeknya Mas. Contohnya seperti ini Mas, https://github.com/jefrydco/jefrydco/blob/master/README.md

Hasilnya nanti akan seperti berikut:

![jefrydco](https://user-images.githubusercontent.com/20434351/89712748-0c804280-d9bd-11ea-8623-505f3e98fa15.png)

Pada berkas tersebut Mas juga dapat menuliskan deskripsi seputar aplikasi pada repo ini dan bagaimana cara menjalankannya. Mas dapat menggunakan penulisan [berformat markdown](https://guides.github.com/features/mastering-markdown/) atau HTML.

Semangat Mas! 😄

**Comment by cjzeven** [comment]
Hi mas Jefry. Wah terima kasih atas feedbacknya. 
Baik, saya akan coba menambahkan deskripsi tentang repo tsb.

Terima kasih 😃

**Comment by cjzeven** [comment]
Readme and license file was added
